---
- hosts: localhost
  tasks:
     - name: create VPC
       ec2_vpc_net:
          aws_access_key: AKIAU3HD7MCVANO56LQ3
          aws_secret_key: 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
          name: "vpc-subnet"
          cidr_block: 10.10.10.0/16
          region: us-east-2
          state: present
       register: vpc
    # - name: print
    #   debug:
    #       msg: "{{ vpc.vpc.id }}"
     - name: associate subnet to the VPC
       ec2_vpc_subnet:
         state: present
         vpc_id: "{{ vpc.vpc.id }}"
         region: us-east-2
         cidr: 10.10.1.0/24
         aws_access_key: AKIAU3HD7MCVANO56LQ3
         aws_secret_key: 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
         map_public: yes
         resource_tags:
            Name: ansible-subnet
       register: subnet

#------------------------------------------------------------------------------------------

     - name: create IGW
       community.aws.ec2_vpc_igw:
            aws_access_key: AKIAU3HD7MCVANO56LQ3
            aws_secret_key: 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
            vpc_id: "{{ vpc.vpc.id }}"
            region: us-east-2
            state: "present"
            tags:
                Name: igw-ansible
       register: igw
#--------------------------------------------------------------------------------------------

     - name: Route IGW
       ec2_vpc_route_table:
         vpc_id: "{{ vpc.vpc.id }}"
         aws_access_key: AKIAU3HD7MCVANO56LQ3
         aws_secret_key: 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
         region: us-east-2
         subnets:
           - "{{ subnet.subnet.id }}"
         routes:
           - dest: 0.0.0.0/0
             gateway_id: "{{ igw.gateway_id  }}"
         tags:
             Name: ansible-route
#-----------------------------------------------------------------------------------------------


     - name: Create Security Group
       ec2_group:
           name: Web DMZ
           aws_access_key: AKIAU3HD7MCVANO56LQ3
           aws_secret_key: 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

           description: DMZ Security Group
           vpc_id: "{{ vpc.vpc.id }}"
           region: us-east-2
           #aws_access_key: "{{ aws_access_key }}"
           #aws_secret_key: "{{ aws_secret_key }}"
           rules:
              - proto: tcp
                ports:
                 - 80
                cidr_ip: 0.0.0.0/0
              - proto: tcp
                ports:
                  - 22
                cidr_ip: 0.0.0.0/0
       register: security_group




#----------------------------------------------------------------------------------

     - name: create a new ec2 key pair
       ec2_key:
          #aws_access_key: "{{ aws_access_key }}"
          #aws_secret_key: "{{ aws_secret_key }}"
          aws_access_key: AKIAU3HD7MCVANO56LQ3
          aws_secret_key: 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

          name: ec2_keypair
          region: us-east-2
       register: keypair

    # - name: Copy EC2 Private Key locally so it can be later on used to SSH into the instance
    #   copy: content="{{ keypair.key.private_key }}" dest={{ ec2_key_directory }}key.pem
    #   when: keypair.changed == true
#-------------------------------------------------------------------------------------------


     - name: Create EC2 server
       ec2:
         image: ami-00399ec92321828f5
         wait: yes
         aws_access_key: AKIAU3HD7MCVANO56LQ3
         aws_secret_key: 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

         instance_type: t2.micro
         region: us-east-2
         group_id: "{{ security_group.group_id }}"
         vpc_subnet_id: "{{ subnet.subnet.id }}"
         key_name: "{{ keypair.key.name  }}"
         aws_access_key: AKIAU3HD7MCVMQSZ5NWS
         aws_secret_key: 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
         count_tag:
           Name: ansible-instance
         exact_count: 1
         user_data: "#!/bin/bash \n sudo apt-get update \n sudo apt-get install -y docker.io  \n sudo docker run --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d nginx \n "
root@LAPTOP-FHA1MPGT:/etc/ansible#